# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3aedf2406f5d738397630c37fa11396854592e11b144a834b159de5f6936bcd1983ca5029adbbd411c4c8460db65acef9bba9c48f57b2eb5e41f7006de40db2b

test:
  secret_key_base: d50ac2371626985b29d429f2e5431d0a3328e62737d4f63af9d8150178fa54c3d8b345ec2339a808c3bddd54661229a43c82720aadc83c754fb834194d0634f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
